name: Environment Promotion

on:
  workflow_dispatch:
    inputs:
      from_env:
        description: 'Source environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
      to_env:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - prod

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Environment
        run: |
          ./scripts/promote.sh ${{ github.event.inputs.from_env }} ${{ github.event.inputs.to_env }}
