name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-apply.yml'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform init (dev)
        run: terraform -chdir=terraform/environments/dev init -input=false -reconfigure

      - name: Terraform apply (dev)
        if: github.event_name == 'workflow_dispatch'
        run: terraform -chdir=terraform/environments/dev apply -auto-approve -input=false -no-color

      - name: Terraform apply on main (dev)
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform/environments/dev apply -auto-approve -input=false -no-color 